package com.mybatis.generate.domain;

public class User {
    /**
     * <pre>
     * 自增主键
     * 表字段 : tb_book_login.id
     * </pre>
     * 
     */
    private Integer id;

    /**
     * <pre>
     * 老师id
     * 表字段 : tb_book_login.teacher_id
     * </pre>
     * 
     */
    private String teacherId;

    /**
     * <pre>
     * 老师名称
     * 表字段 : tb_book_login.teacher_name
     * </pre>
     * 
     */
    private String teacherName;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_book_login.id
     *
     * @return the value of tb_book_login.id
     *
     * @mbg.generated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_book_login.id
     *
     * @param id the value for tb_book_login.id
     *
     * @mbg.generated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_book_login.teacher_id
     *
     * @return the value of tb_book_login.teacher_id
     *
     * @mbg.generated
     */
    public String getTeacherId() {
        return teacherId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_book_login.teacher_id
     *
     * @param teacherId the value for tb_book_login.teacher_id
     *
     * @mbg.generated
     */
    public void setTeacherId(String teacherId) {
        this.teacherId = teacherId == null ? null : teacherId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_book_login.teacher_name
     *
     * @return the value of tb_book_login.teacher_name
     *
     * @mbg.generated
     */
    public String getTeacherName() {
        return teacherName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_book_login.teacher_name
     *
     * @param teacherName the value for tb_book_login.teacher_name
     *
     * @mbg.generated
     */
    public void setTeacherName(String teacherName) {
        this.teacherName = teacherName == null ? null : teacherName.trim();
    }
}